[book]
authors = ["cosmoplankton"]
language = "en"
multilingual = false
src = "src"
title = "Cosmo Drift - A Cosmoplankton Blog"

[output.html]
additional-css = ["theme/css/additional.css",]
additional-js = []
default-theme = "dark"
preferred-dark-theme = "ayu"
no-section-label = true
site-url = "/"
cname = "blog.cosmoplankton.studio"

[output.html.print]
enable = false

[output.html.fold]
enable = true
level = 1
